// component-data/react/vanilla_css/scoped/checkbox/App.js
import {
  Checkbox,
  CheckboxControl,
  CheckboxInput,
  CheckboxLabel,
} from "@ark-ui/react";
import React from "react";

import CheckIcon from "./CheckIcon";
import MinusIcon from "./MinusIcon";
import "./styles.css";

export default function Page() {
  const [checkedItems, setCheckedItems] = React.useState([false, false]);

  const allChecked = checkedItems.every(Boolean);
  const someChecked = checkedItems.some(Boolean) && !allChecked;

  return (
    <>
      <Checkbox
        className="rootStyles"
        checked={allChecked}
        indeterminate={someChecked}
        onChange={(e) =>
          setCheckedItems([e.checked === true, e.checked === true])
        }
      >
        {(state) => (
          <>
            <CheckboxInput className="inputStyles" />
            <CheckboxControl className="controlStyles">
              {state.isChecked && <CheckIcon />}
              {state.isIndeterminate && <MinusIcon />}
            </CheckboxControl>
            <CheckboxLabel className="labelStyles">
              Parent Checkbox
            </CheckboxLabel>
          </>
        )}
      </Checkbox>
      <div>
        <Checkbox
          className="rootStyles"
          checked={checkedItems[0]}
          onChange={(e) =>
            setCheckedItems([e.checked === true, checkedItems[1]])
          }
        >
          {(state) => (
            <>
              <CheckboxInput className="inputStyles" />
              <CheckboxControl className="controlStyles">
                {state.isChecked && <CheckIcon />}
              </CheckboxControl>
              <CheckboxLabel className="labelStyles">
                Child Checkbox 1
              </CheckboxLabel>
            </>
          )}
        </Checkbox>
        <Checkbox
          className="rootStyles"
          checked={checkedItems[1]}
          onChange={(e) =>
            setCheckedItems([checkedItems[0], e.checked === true])
          }
        >
          {(state) => (
            <>
              <CheckboxInput className="inputStyles" />
              <CheckboxControl className="controlStyles">
                {state.isChecked && <CheckIcon />}
              </CheckboxControl>
              <CheckboxLabel className="labelStyles">
                Child Checkbox 2
              </CheckboxLabel>
            </>
          )}
        </Checkbox>
      </div>
    </>
  );
}

// component-data/vue/vanilla_css/scoped/checkbox/App.vue
<script setup>
import {
  Checkbox,
  CheckboxControl,
  CheckboxInput,
  CheckboxLabel,
} from "@ark-ui/vue";
import { computed, reactive } from "vue";

import CheckIcon from "./CheckIcon.vue";
import MinusIcon from "./MinusIcon.vue";

import "./styles.css";

const checkedItems = reactive([false, false]);

const allChecked = computed(() => checkedItems.every(Boolean));
const someChecked = computed(() => checkedItems.some(Boolean)) && !allChecked;
</script>

<template>
  <Checkbox
    class="rootStyles"
    @change="
      (checked) => {
        checkedItems[0] = checked;
        checkedItems[1] = checked;
      }
    "
    v-model:checked="allChecked"
    v-model:indeterminate="someChecked"
    v-slot="{ isChecked, isIndeterminate }"
  >
    <CheckboxInput class="inputStyles" />
    <CheckboxControl class="controlStyles">
      <CheckIcon v-if="isChecked" />
      <MinusIcon v-if="isIndeterminate" />
    </CheckboxControl>
    <CheckboxLabel class="labelStyles">Parent Checkbox</CheckboxLabel>
  </Checkbox>
  <div>
    <Checkbox
      class="rootStyles"
      v-model:checked="checkedItems[0]"
      v-slot="{ isChecked }"
    >
      <CheckboxInput class="inputStyles" />
      <CheckboxControl class="controlStyles">
        <CheckIcon v-if="isChecked" />
      </CheckboxControl>
      <CheckboxLabel class="labelStyles">Child Checkbox 1</CheckboxLabel>
    </Checkbox>
    <Checkbox
      class="rootStyles"
      v-model:checked="checkedItems[1]"
      v-slot="{ isChecked }"
    >
      <CheckboxInput class="inputStyles" />
      <CheckboxControl class="controlStyles">
        <CheckIcon v-if="isChecked" />
      </CheckboxControl>
      <CheckboxLabel class="labelStyles">Child Checkbox 2</CheckboxLabel>
    </Checkbox>
  </div>
</template>
